/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue.ActionsPossibles;

import Controleur.Controleur;

/**
 *
 * @author Loïc Cimon
 */
public class PanelChoixCase extends javax.swing.JPanel {

    /**
     * Creates new form PanelChoixCase
     */
    public PanelChoixCase() {
        initComponents();
    }

    public static void setValidationPossible(boolean etat) {
        boutonOk.setEnabled(etat);
    }

    public static void setBatiment(String nom) {
        batiment.setText("Batiment à activer : " + nom);
        batiment.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonOk = new javax.swing.JLabel();
        boutonAnnuler = new javax.swing.JLabel();
        batiment = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 246, 199));
        setLayout(new java.awt.BorderLayout(5, 0));

        boutonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ok.png"))); // NOI18N
        boutonOk.setText("Valider placement");
        boutonOk.setEnabled(false);
        boutonOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boutonOk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boutonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonOkMouseClicked(evt);
            }
        });
        add(boutonOk, java.awt.BorderLayout.LINE_START);

        boutonAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        boutonAnnuler.setText("Passer son tour");
        boutonAnnuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boutonAnnuler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boutonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonAnnulerMouseClicked(evt);
            }
        });
        add(boutonAnnuler, java.awt.BorderLayout.LINE_END);

        batiment.setFont(new java.awt.Font("Vivaldi", 1, 22)); // NOI18N
        batiment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batiment.setText(" Choissisez une case.");
        add(batiment, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonOkMouseClicked
        //Utile lors de la phase 2 et 3
        if (boutonOk.isEnabled()
                && (Controleur.getInstance().getPhase() == 2 || Controleur.getInstance().getPhase() == 3)) {
            Controleur.getInstance().placerOuvrier();
            Controleur.getInstance().click();
        }
    }//GEN-LAST:event_boutonOkMouseClicked

    private void boutonAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonAnnulerMouseClicked
        //Utile lors de la phase 2
        if (Controleur.getInstance().getPhase() == 2) {
            Controleur.getInstance().finDePose();
        }
        Controleur.getInstance().click();
    }//GEN-LAST:event_boutonAnnulerMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel batiment;
    private javax.swing.JLabel boutonAnnuler;
    private static javax.swing.JLabel boutonOk;
    // End of variables declaration//GEN-END:variables

}
