/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue.ActionsPossibles;

import Controleur.Controleur;
import Vue.Plateau;

/**
 *
 * @author Loïc Cimon
 */
public class PanelPlacementOuvriers extends javax.swing.JPanel {

    /**
     * Creates new form PanelPlacementOuvriers
     */
    public PanelPlacementOuvriers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonOk = new javax.swing.JLabel();
        boutonAnnuler = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 246, 199));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        boutonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ok.png"))); // NOI18N
        boutonOk.setText("Valider placement");
        boutonOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boutonOk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boutonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonOkMouseClicked(evt);
            }
        });
        add(boutonOk);

        boutonAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        boutonAnnuler.setText("Passer son tour");
        boutonAnnuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boutonAnnuler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boutonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonAnnulerMouseClicked(evt);
            }
        });
        add(boutonAnnuler);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonOkMouseClicked
        Controleur.getInstance().placerOuvrier();
        Controleur.getInstance().click();
    }//GEN-LAST:event_boutonOkMouseClicked

    private void boutonAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonAnnulerMouseClicked
        Controleur.getInstance().passerSonTour();
    }//GEN-LAST:event_boutonAnnulerMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boutonAnnuler;
    private javax.swing.JLabel boutonOk;
    // End of variables declaration//GEN-END:variables
}
