/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Joueur;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.*;

/**
 *
 * @author Carlito De La Vega
 */
public class InterfaceJoueur extends javax.swing.JPanel {

    /**
     * Creates new form InterfaceJoueur
     */
    private Joueur joueur;

    public InterfaceJoueur(Joueur j) {
        this.joueur = j;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPhaseJeu = new JLabel();
        phaseJeu = new JLabel();
        jPanel1 = new JPanel();
        pierre = new JLabel();
        nourriture = new JLabel();
        deniers = new JLabel();
        tissu = new JLabel();
        prestige = new JLabel();
        ressources = new JLabel();
        labelDenierPrestige = new JLabel();
        or = new JLabel();
        bois = new JLabel();
        labelNomJoueur = new JLabel();
        nomJoueur = new JLabel();
        couleurJoueur = new JLabel();
        labelPhaseJeu1 = new JLabel();
        panelActions = new JPanel();

        setBackground(new Color(254, 246, 199));

        labelPhaseJeu.setFont(new Font("Vivaldi", 1, 24));         labelPhaseJeu.setText("Phase de jeu :");

        phaseJeu.setFont(new Font("Vivaldi", 0, 24));         phaseJeu.setText("phase");

        jPanel1.setBackground(new Color(254, 246, 199));
        jPanel1.setBorder(BorderFactory.createEtchedBorder());

        pierre.setFont(new Font("Vivaldi", 0, 14));         pierre.setHorizontalAlignment(SwingConstants.CENTER);
        pierre.setIcon(new ImageIcon(getClass().getResource("/Image/Ressources/pierre.jpg")));         pierre.setText(String.valueOf(joueur.getNbRessource("Pierre")));
        pierre.setHorizontalTextPosition(SwingConstants.CENTER);
        pierre.setVerticalTextPosition(SwingConstants.BOTTOM);

        nourriture.setFont(new Font("Vivaldi", 0, 14));         nourriture.setHorizontalAlignment(SwingConstants.CENTER);
        nourriture.setIcon(new ImageIcon(getClass().getResource("/Image/Ressources/nourriture.jpg")));         nourriture.setText(String.valueOf(joueur.getNbRessource("Nourriture")));
        nourriture.setHorizontalTextPosition(SwingConstants.CENTER);
        nourriture.setVerticalTextPosition(SwingConstants.BOTTOM);

        deniers.setFont(new Font("Vivaldi", 0, 14));         deniers.setHorizontalAlignment(SwingConstants.CENTER);
        deniers.setIcon(new ImageIcon(getClass().getResource("/Image/denier.jpg")));         deniers.setText(String.valueOf(joueur.getNbDenier()));
        deniers.setHorizontalTextPosition(SwingConstants.CENTER);
        deniers.setVerticalTextPosition(SwingConstants.BOTTOM);

        tissu.setFont(new Font("Vivaldi", 0, 14));         tissu.setHorizontalAlignment(SwingConstants.CENTER);
        tissu.setIcon(new ImageIcon(getClass().getResource("/Image/Ressources/tissu.jpg")));         tissu.setText(String.valueOf(joueur.getNbRessource("Tissu")));
        tissu.setHorizontalTextPosition(SwingConstants.CENTER);
        tissu.setVerticalTextPosition(SwingConstants.BOTTOM);

        prestige.setFont(new Font("Vivaldi", 0, 14));         prestige.setHorizontalAlignment(SwingConstants.CENTER);
        prestige.setIcon(new ImageIcon(getClass().getResource("/Image/prestige.jpg")));         prestige.setText(String.valueOf(joueur.getNbPrestige()));
        prestige.setHorizontalTextPosition(SwingConstants.CENTER);
        prestige.setVerticalTextPosition(SwingConstants.BOTTOM);

        ressources.setFont(new Font("Vivaldi", 0, 18));         ressources.setText("Ressources :");

        labelDenierPrestige.setFont(new Font("Vivaldi", 0, 18));         labelDenierPrestige.setText("Deniers et prestiges :");

        or.setFont(new Font("Vivaldi", 0, 14));         or.setHorizontalAlignment(SwingConstants.CENTER);
        or.setIcon(new ImageIcon(getClass().getResource("/Image/Ressources/or.jpg")));         or.setText(String.valueOf(joueur.getNbRessource("Or")));
        or.setHorizontalTextPosition(SwingConstants.CENTER);
        or.setVerticalTextPosition(SwingConstants.BOTTOM);

        bois.setFont(new Font("Vivaldi", 0, 14));         bois.setHorizontalAlignment(SwingConstants.CENTER);
        bois.setIcon(new ImageIcon(getClass().getResource("/Image/Ressources/bois.jpg")));         bois.setText(String.valueOf(joueur.getNbRessource("Bois")));
        bois.setHorizontalTextPosition(SwingConstants.CENTER);
        bois.setVerticalTextPosition(SwingConstants.BOTTOM);

        labelNomJoueur.setFont(new Font("Vivaldi", 1, 20));         labelNomJoueur.setText("Au tour de :");

        nomJoueur.setFont(new Font("Vivaldi", 0, 20));         nomJoueur.setText(joueur.getNom());

        couleurJoueur.setIcon(new ImageIcon(getClass().getResource("/Image/Marqueur/"+joueur.getCouleur()+".jpg")));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deniers, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(prestige))
                    .addComponent(labelDenierPrestige)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nourriture)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(bois)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(pierre)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(tissu)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(or))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNomJoueur)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(nomJoueur)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(couleurJoueur))
                    .addComponent(ressources))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(labelNomJoueur)
                        .addComponent(nomJoueur))
                    .addComponent(couleurJoueur))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(ressources)
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(nourriture, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                    .addComponent(bois, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pierre, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tissu, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                    .addComponent(or, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(labelDenierPrestige)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(prestige)
                    .addComponent(deniers, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        labelPhaseJeu1.setFont(new Font("Vivaldi", 1, 24));         labelPhaseJeu1.setText("Actions possibles :");

        panelActions.setBackground(new Color(254, 246, 199));
        panelActions.setBorder(BorderFactory.createEtchedBorder());

        GroupLayout panelActionsLayout = new GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPhaseJeu)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(phaseJeu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                            .addComponent(panelActions, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPhaseJeu1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(labelPhaseJeu)
                    .addComponent(phaseJeu))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(labelPhaseJeu1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(panelActions, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel bois;
    private JLabel couleurJoueur;
    private JLabel deniers;
    private JPanel jPanel1;
    private JLabel labelDenierPrestige;
    private JLabel labelNomJoueur;
    private JLabel labelPhaseJeu;
    private JLabel labelPhaseJeu1;
    private JLabel nomJoueur;
    private JLabel nourriture;
    private JLabel or;
    private JPanel panelActions;
    private JLabel phaseJeu;
    private JLabel pierre;
    private JLabel prestige;
    private JLabel ressources;
    private JLabel tissu;
    // End of variables declaration//GEN-END:variables

    public void majInformations(Joueur j) {
        this.joueur = j;

        // Nom du joueur
        this.nomJoueur.setText(joueur.getNom());
        // Couleur du joueur
        this.couleurJoueur.setIcon(new ImageIcon(getClass().getResource("/Image/Marqueur/"+joueur.getCouleur()+".jpg")));
        // Nourriture
        this.nourriture.setText(String.valueOf(joueur.getNbRessource("Nourriture")));
        // Bois
        this.bois.setText(String.valueOf(joueur.getNbRessource("Bois")));
        // Pierre 
        this.pierre.setText(String.valueOf(joueur.getNbRessource("Pierre")));
        // Tissu
        this.tissu.setText(String.valueOf(joueur.getNbRessource("Tissu")));
        // Or
        this.or.setText(String.valueOf(joueur.getNbRessource("Or")));
        // Deniers
        this.deniers.setText(String.valueOf(joueur.getNbDenier()));
        // Prestige
        this.prestige.setText(String.valueOf(joueur.getNbPrestige()));
        
        this.repaint();
    }
    
    public void setPhase(String phase) {
        this.phaseJeu.setText(phase);
        this.repaint();
    }
    
    public void setPanelAction(JPanel action) {
        panelActions.setLayout(new BorderLayout());
        this.panelActions.add(action, BorderLayout.CENTER);
    }
}
