/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.Controleur;
import Modele.Joueur;
import Modele.Lot;
import Modele.Ressource;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Loïc Cimon
 */
public class PanelCreationLot extends javax.swing.JDialog {

    private Joueur joueur;
    private Lot lot;

    /**
     * Creates new form PanelCreationLot
     */
    public PanelCreationLot(Joueur joueur) {
        super((Fenetre) Controleur.getInstance().getPlateau().getTopLevelAncestor(), true);
        this.joueur = joueur;

        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    public String[] getModelInitial() {
        List<String> tmp = new ArrayList<>();
        Ressource r;
        for (Iterator<Ressource> iRes = joueur.getRessources().values().iterator(); iRes.hasNext();) {
            r = iRes.next();
            if (r.getQuantite() > 0) {
                tmp.add(r.getNom());
            }
        }

        String[] res = new String[tmp.size()];
        tmp.toArray(res);
        return res;
    }

    public Lot getLot() {
        return lot;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ressource1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ressource2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ressource3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 246, 199));
        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));

        titre.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Créer un lot");
        titre.setMaximumSize(new java.awt.Dimension(162, 75));
        titre.setPreferredSize(new java.awt.Dimension(162, 75));
        jPanel1.add(titre, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(254, 246, 199));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel1.setText("Choissisez les ressources de votre lot :");

        jPanel3.setBackground(new java.awt.Color(254, 246, 199));
        jPanel3.setLayout(new java.awt.GridLayout(1, 5, 0, 10));

        ressource1.setModel(new javax.swing.DefaultComboBoxModel(this.getModelInitial()));
        ressource1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ressource1ActionPerformed(evt);
            }
        });
        jPanel3.add(ressource1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        jPanel3.add(jLabel4);

        ressource2.setModel(new javax.swing.DefaultComboBoxModel(this.getModelInitial()));
        ressource2.setEnabled(false);
        ressource2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ressource2ActionPerformed(evt);
            }
        });
        jPanel3.add(ressource2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        jPanel3.add(jLabel5);

        ressource3.setModel(new javax.swing.DefaultComboBoxModel(this.getModelInitial()));
        ressource3.setEnabled(false);
        jPanel3.add(ressource3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ressources/tissu.jpg"))); // NOI18N
        jLabel2.setText("1");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(254, 246, 199));
        jPanel4.setPreferredSize(new java.awt.Dimension(461, 75));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 40, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ok.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ressource1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ressource1ActionPerformed
        ressource2.setModel(new javax.swing.DefaultComboBoxModel(this.getModelInitial()));
        ressource2.removeItem(ressource1.getSelectedItem());
        ressource2.setEnabled(true);
    }//GEN-LAST:event_ressource1ActionPerformed

    private void ressource2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ressource2ActionPerformed
        ressource3.setModel(ressource2.getModel());
        ressource3.removeItem(ressource1.getSelectedItem());
        ressource3.removeItem(ressource2.getSelectedItem());
        ressource3.setEnabled(true);
    }//GEN-LAST:event_ressource2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        lot = new Lot((String)ressource1.getSelectedItem(), (String)ressource2.getSelectedItem(), (String)ressource3.getSelectedItem());
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox ressource1;
    private javax.swing.JComboBox ressource2;
    private javax.swing.JComboBox ressource3;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
